version: "3"

services:
    jenkins:
        container_name: jenkins
        build: ./jenkins
        networks: 
            - myjenkinsnet
        volumes:
            - jenkins-data:/var/jenkins_home
            - jenkins-log:/var/log/jenkins
        environment:
            JENKINS_ADMIN_ID: admin
            JENKINS_ADMIN_PASSWORD: mehdi2020
            SSH_KEY_PASSWORD: fakekeypass
        ports:
            - 8088:8080
            - 50000:50000

networks:
    myjenkinsnet:
        driver: bridge
    
volumes:
    jenkins-data:
    jenkins-log: