FROM jenkins/jenkins:2.277.1-lts-jdk11
USER root
RUN apt-get update && apt-get install -y apt-transport-https \
       ca-certificates curl gnupg2 \
       software-properties-common
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN apt-key fingerprint 0EBFCD88
RUN add-apt-repository \
       "deb [arch=amd64] https://download.docker.com/linux/debian \
       $(lsb_release -cs) stable"
RUN apt-get update && apt-get install -y docker-ce-cli
USER jenkins
ENV JENKINS_UC_DOWNLOAD="http://ftp-nyc.osuosl.org/pub/jenkins"
ENV CURL_OPTIONS -sSfLk -C -
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
#ENV SECRETS="/var/jenkins_home/"
ENV CASC_JENKINS_CONFIG /usr/share/jenkins/ref/casc.yaml
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
#COPY id_ed25519 /var/jenkins_home/jenkins-ssh-keys/ssh-agent-access-key
COPY casc.yaml /usr/share/jenkins/ref/casc.yaml
#RUN jenkins-plugin-cli --plugins "blueocean:1.24.5 docker-workflow:1.26"